# Generated by Django 4.2.1 on 2023-06-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
